FROM golang:1.25.0-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    vim \
    curl \
    less \
    unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

CMD ["bash", "-l"]
